/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-tint": "var(--color-surface-tint)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "primary": "var(--color-primary)",
        "on-primary": "var(--color-on-primary)",
        "surface-dim": "var(--color-surface-dim)",
        "on-surface": "var(--color-on-surface)",
        "on-secondary": "var(--color-on-secondary)",
        "primary-container": "var(--color-primary-container)",
        "primary-fixed": "var(--color-primary-fixed)",
        "background": "var(--color-background)",
        "error": "var(--color-error)",
        "tertiary-container": "var(--color-tertiary-container)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-error-container": "var(--color-on-error-container)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-primary-container": "var(--color-on-primary-container)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "surface-bright": "var(--color-surface-bright)",
        "tertiary": "var(--color-tertiary)",
        "on-background": "var(--color-on-background)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface": "var(--color-surface)",
        "error-container": "var(--color-error-container)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "secondary": "var(--color-secondary)",
        "secondary-container": "var(--color-secondary-container)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-error": "var(--color-on-error)",
        "outline": "var(--color-outline)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-container": "var(--color-surface-container)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "inverse-surface": "var(--color-inverse-surface)"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "24px",
        "unit": "8px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "container-margin-desktop": "64px",
        "container-margin-mobile": "20px",
        "stack-sm": "8px"
      },
      "fontFamily": {
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        "label-md": ["Inter"]
      },
      "fontSize": {
        "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "headline-sm": ["20px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500"}]
      }
    },
  },
}
